version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    image: danishyousuf/node-app
  #  platform: linux/amd64
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  
  redis: 
    image: redis

volumes:
  mongo-db:    



