version: '3.8'
services:
  node-app:
    build: .
    ports:
      - "3002:4000"
    environment:
      - PORT=4000
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:    



