version: '3.8'
services:
  node-app:
    build: .
    environment:
      - PORT=4000
    # env_file:
    #   - ./.env
    ports:
      - "3003:4000"  
    volumes:
      - ./:/app
      - /app/node_modules 
      

      
      